# Generated by Django 3.1.3 on 2020-12-02 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0003_auto_20201118_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 1)),
        ),
    ]
